loomx.loom_version = "1.16-SNAPSHOT"

deps.fabric_loader = "0.17.2"
deps.topper = "4.19.1"
deps.hscore = "4.8.1"
deps.configurate = "4.2.0"

["1.21.11"]
deps.fabric_api = "0.141.2+1.21.11"
deps.text_placeholder_api = "2.8.2+1.21.10"
deps.permissions_api = "0.6.1"
deps.mini_placeholders = "3.0.1"
deps.adventure_fabric = "6.8.0"
deps.faststats = "0.1.0+1.21.11"
mod.mc_dep = ">=1.21.11 <=1.21.11"
mod.mc_title = "1.21.11"
mod.mc_targets = "1.21.11"

["26.1.2"]
deps.fabric_api = "0.146.1+26.1.2"
deps.text_placeholder_api = "3.0.0+26.1"
deps.permissions_api = "0.7.0"
deps.mini_placeholders = "3.2.0"
deps.adventure_fabric = "6.9.0"
deps.faststats = "0.1.0+26.1.2"
mod.mc_dep = ">=26.1 <=26.1.2"
mod.mc_title = "26.1.2"
mod.mc_targets = "26.1 26.1.1 26.1.2"